### ISSUE TITLE
Loops and Collections episode: make list representation in _config.yml consistent

### ISSUE THREAD

**Issue by anenadic** [carpentries-incubator/jekyll-pages-novice#211]
- We are inconsistent in how we represent lists/dictionaries in YAML in team_members site variable and collections: [posts: {output: true}] in "Configuring a Collection" section. Suggestion: use the latter in both cases?

**Comment by tobyhodges** [comment]
http://yamllint.com changes

```yaml
collections: [
    blogposts: {output: true},
    posts: {output: true}
]
```

to

```
collections: 
  - 
    blogposts: 
      output: true
  - 
    posts: 
      output: true
```

and in most of the documentation I have seen, this is the way lists are represented in YAML. I think it would be better to follow the convention in our lesson too, to expose learners to the format they are most likely to encounter "in the wild."
