### ISSUE TITLE
Fix collection config

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/jekyll-pages-novice#254]
I ran into trouble while creating screenshots for the Loops & Collections episode, and found that I needed to write the YAML config for the `blogposts` collections as:

```YAML
collections:
  blogposts:
    output: true
```

instead of 

```YAML
collections:
  -
    blogposts:
      -
        output: true
```

as I had written in the lesson. This needs to be fixed and the explanatory text that goes with it needs to be updated to be accurate.
